train-sklearn:
#  classifier: RandomForestClassifier
  classifier: DecisionTreeClassifier
  parameters:
    criterion: entropy
    max_depth: 600
    min_samples_split: 5
  target_opset: 16

train-pytorch:
  model_type: NN
  #model_type: ResNet
  batch_size: 16
  learning_rate: 1e-6
  epochs: 3
  target_opset: 16
  #in_channels: 16
  #out_channels: 16

hyperopt:
  target_opset: 16
